name: test-on-push-and-pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run 'pr' target
      run: make pr

  alpine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run alpine integration tests
      run: DISTRO=alpine make test-integ
